name: Deployment Workflow
on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
      TF_API_TOKEN:
        required: true
        type: string
      GITHUB_TOKEN:
        required: true
        type: string  
      AWS_ACCESS_KEY_ID:
        required: true
        type: string  
      AWS_SECRET_ACCESS_KEY:
        required: true
        type: string                
runs:
  using: composite
  steps:
    - uses: ./.github/workflows/deploy_application_workflow/terraform_setup
      with:
        aws_region: ${{ matrix.aws_region }}
        TF_API_TOKEN: ${{ inputs.TF_API_TOKEN }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - uses: ./.github/workflows/deploy_application_workflow/terraform_apply
      with:
        aws_region: ${{ matrix.aws_region }}      
        TF_API_TOKEN: ${{ inputs.TF_API_TOKEN }}

    - uses: ./.github/workflows/deploy_application_workflow/setup_global_accelerator
      with:
        aws_region: ${{ matrix.aws_region }}      
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}  
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}  

    - uses: ./.github/workflows/deploy_application_workflow/deploy_application
      with:
        aws_region: ${{ matrix.aws_region }}
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}  
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}  